### ISSUE TITLE
Question about license of geofeed database

### ISSUE THREAD

**Issue by sapics** [chriselsen/AWS-Geofeed#3]
Thank you for your great works!

I have a question about license of your created geofeed database.

I would like to use your created geofeed database in [repository](https://github.com/sapics/ip-location-db)'s database which is published in [Creative Commons Zero License](https://creativecommons.org/publicdomain/zero/1.0/deed).
When I make a link to this repository in my repository, can we published our database in CC0 which includes this geofeed database?

(I am not good at English, so I apologize if I am rude in any way.)

**Comment by sapics** [comment]
I close this issue, because I find similar database which has no license restriction.

**Comment by chriselsen** [comment]
License was changed to [Creative Commons Zero v1.0 Universal](https://github.com/chriselsen/AWS-Geofeed/blob/main/LICENSE)
